backend:
  name: git-gateway

media_folder: "static/img/uploads" # Where media files will be stored
public_folder: "/img/uploads" # Start of the src attribute for uploaded media

collections:
  - label: "Post" # Used in the UI
    name: "post" # Used in routes, e.g., /admin/collections/blog
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Homepage" # UI
    name: "homepage" # Used in routes, e.g., /admin/collections/blog
    create: false
    files:
      - file: "content/_index.md"
        label: "Edit Sections"
        name: "sections"
        fields:
          - {label: "About", name: about, widget: object, fields: [
              {label: "Heading", name: "heading", widget: "string"}, 
              {label: "Text", name: "text", widget: "markdown"},
              {label: "Address", name: address, widget: object, fields: [
                {label: "Line 1", name: "line1", widget: "string"}, 
                {label: "Line 2", name: "line2", widget: "string"},
                {label: "Google Maps", name: gmaps, widget: "string"}]},
              {label: "Phone", name: phone, widget: "string"},
              {label: "Hours", name: hours, widget: object, fields: [
                {label: "Sunday", name: "sun", widget: "string"}, 
                {label: "Monday", name: "mon", widget: "string"}, 
                {label: "Tuesday", name: "tue", widget: "string"}, 
                {label: "Wednesday", name: "wed", widget: "string"}, 
                {label: "Thursday", name: "thu", widget: "string"}, 
                {label: "Friday", name: "fri", widget: "string"}, 
                {label: "Saturday", name: "sat", widget: "string"}]}
          ]}
          - {label: "Specials", name: specials, widget: object, fields: [
              {label: "Heading", name: "heading", widget: "string"}, 
              {label: "Text", name: "text", widget: "markdown"}
          ]}
          - {label: "Menu", name: cuisine, widget: object, fields: [
              {label: "Heading", name: "heading", widget: "string"}, 
              {label: "Text", name: "text", widget: "markdown"}
          ]}
          - {label: "Events", name: events, widget: object, fields: [
              {label: "Heading", name: "heading", widget: "string"}, 
              {label: "Text", name: "text", widget: "markdown"}
          ]}
          - {label: "Catering", name: catering, widget: object, fields: [
              {label: "Heading", name: "heading", widget: "string"}, 
              {label: "Text", name: "text", widget: "markdown"}
          ]}
          # - {label: "Photos", name: photos, widget: object, fields: [
          #     {label: "Heading", name: "heading", widget: "string"}, 
          #     {label: "Image", name: "image", widget: "list",
          #       field: {label: "Image", name: "image", widget: "image"} 
          #     }
          # ]}
          - {label: "Contact", name: "contact", widget: object, fields: [
              {label: "Heading", name: "heading", widget: "string"}, 
              {label: "Text", name: "text", widget: "markdown"},
              {label: "Email", name: "email", widget: "string"}
          ]}

  # - label: "Menu"
  #   name: "cuisine"
  #   create: true
  #   files:
  #     - file: "content/_index.md"
  #       label: "Salads"
  #       name: "salads"
  #       fields:
  #         - {label: Heading, name: heading, widget: string}
  #         - {label: Text, name: text, widget: markdown}
  #         - label: Items
  #           name: items
  #           widget: list
  #           fields:
  #             - {label: Salads, name: salads, widget: object, fields: [
  #                 {label: Item Name, name: name, widget: string}
  #                 {label: Description, name: description, widget: text}
  #                 {label: Price, name: price, widget: "number", valueType: "float", step: 0.01}]}
  # - label: "Menu"
  #   name: "cuisine"
  #   create: true
  #   files:
  #     - file: "content/_index.md"
  #       label: "Salads"
  #       name: "salads"
  #       fields:
  #         - {label: "Heading", name: "heading", widget: "string"}
  #         - {label: "Text", name: "text", widget: "markdown"}
  #         - {label: "Title", name: name, widget: "string"},
  #         - {label: "Item Name", name: name, widget: "string"},
  #         - {label: "Description", name: description, widget: "string"},
  #         - {label: "Price", name: price, widget: "number", valueType: "float", step: 0.01}