backend:
  name: git-gateway

media_folder: "static/img/uploads" # Where media files will be stored
public_folder: "/img/uploads" # Start of the src attribute for uploaded media

collections:
  - label: "Post" # Used in the UI
    name: "post" # Used in routes, e.g., /admin/collections/blog
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - label: "Sections" # UI
    name: "sections" # Used in routes, e.g., /admin/collections/blog
    create: false
    files:
      - file: "content/_index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "About", name: about, widget: object, fields: [
              {label: "Heading", name: "heading", widget: "string"}, 
              {label: "Text", name: "text", widget: "markdown"}]}
          - {label: "Google Maps Search", name: gmaps, widget: "string"}
          - {{label: "Address Line 1", name: address1, widget: object, fields: [
              {label: "Line 1", name: "address1", widget: "string"}, 
              {label: "Line 2", name: "address2", widget: "string"}]}